[package]
name = "annad"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "annad"
path = "src/main.rs"

[dependencies]
anna_common = { path = "../anna_common" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
sysinfo = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
notify = { workspace = true }
